### ISSUE TITLE
[Update] membership level

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/oma-knowledge-base#414]
Content to update: https://www.openmobilealliance.org/omaspecworks/membership/benefits#unveiling-omas-membership-since-2002

@gocadimic Seth has identified we still have a reference to the old membership levels. See the above link.
Please update this content to align it with the new membership levels. The content is available in the same page.

**Comment by gocadimic** [comment]
@jpradocueva, The section titled "Unveiling OMA's Membership Since 2002" refers to membership structure levels historically, and in the next section, "Membership Structure Update 2025," we explain the actual one.
I think it is essential for the old members to understand the change and the new structure levels.

**Comment by jpradocueva** [comment]
@gocadimic Hi Gordana, as this request came from Seth, please check with him. I believe that he sees it differently. Please send him an email and CC me so I can participate in the discussion if needed.

**Comment by gocadimic** [comment]
Resolved in PR #418

**Comment by gocadimic** [comment]
Merged --> closing issue
